import type { SymmetryGlossaryEntry } from './types.ts';

/** What a group is, how it is named, and the groups worth knowing by name. */
export const GROUP_TERMS: Record<string, SymmetryGlossaryEntry> = {
  group: {
    title: 'Group',
    summary:
      'A set of operations closed under composition, containing the identity, giving every operation an inverse, and associative. The symmetry operations of any object satisfy all four on their own, which is why group theory says anything about molecules at all.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'E, C2, σv(xz), σv′(yz): multiply any two, stay inside',
      },
    ],
  },
  'order of a group': {
    title: 'Order, h',
    summary:
      'How many operations the group holds — not how many elements are drawn. It is the divisor in the reduction formula, and the squared dimensions of the irreducible representations add up to it.',
    examples: [
      { object: 'molecule:water', observation: 'h = 4, and 1+1+1+1 = 4' },
      { object: 'molecule:methane', observation: 'h = 24, and 1+1+4+9+9 = 24' },
    ],
  },
  closure: {
    title: 'Closure',
    summary:
      'Two operations of a group done in succession always give a third operation of the same group, never something new. That is what makes a multiplication table square and finite, and why you cannot find one more symmetry once the group is assigned.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'σv(xz) then C2 gives σv′(yz), already in the group',
      },
    ],
  },
  class: {
    title: 'Class',
    summary:
      'Operations that some operation of the group turns into one another. Members of a class share a character in every representation, so a character table has one column per class and never one per operation. The number of classes is also the number of irreducible representations.',
    examples: [
      {
        object: 'molecule:ammonia',
        observation: '6 operations in 3 classes: E, 2C3, 3σv',
      },
      {
        object: 'molecule:benzene',
        observation: 'The C2 through carbons and through bonds are two classes',
      },
    ],
  },
  subgroup: {
    title: 'Subgroup',
    summary:
      'A subset of a group that is itself a group. Its order divides the order of the parent, which is a fast check on any assignment. Lowering the symmetry of a molecule always moves it into a subgroup of where it started.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'Cs and C2 are subgroups of order 2 inside C2v',
      },
    ],
  },
  generator: {
    title: 'Generator',
    summary:
      'An operation, or a few of them, whose repeated composition produces the whole group. C2v is generated by C2 and one mirror plane. A space group is stored the same way, as generators rather than as a list of everything.',
    examples: [
      {
        object: 'spaceGroup:14',
        observation: 'Two generators produce all four general positions',
      },
    ],
  },
  'point group': {
    title: 'Point group',
    summary:
      'The group of operations that leave at least one point fixed — rotations, reflections, inversion and improper rotations, but no translation. Every molecule belongs to one, and 32 of them are compatible with a lattice.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'C2v: all four operations leave the oxygen fixed',
      },
      { object: 'pointGroup:c2v', observation: 'The catalogue entry, in full' },
    ],
  },
  'schoenflies notation': {
    title: 'Schoenflies notation',
    summary:
      'The naming chemists use: a letter for the family, a number for the order of the principal axis, a subscript for the mirror planes. C2v, D3h, Td, Oh. Crystallographers use Hermann–Mauguin instead, and every group has a name in both.',
    examples: [
      {
        object: 'molecule:benzene',
        observation: 'D6h in Schoenflies, 6/mmm in Hermann–Mauguin',
      },
    ],
  },
  'hermann-mauguin notation': {
    title: 'Hermann–Mauguin notation',
    summary:
      'The crystallographic naming: a number for a rotation axis, a bar for an inversion axis, m for a mirror, a slash for a mirror perpendicular to the axis before it. Each position names a fixed direction in the cell, so the order of the characters carries meaning.',
    examples: [
      {
        object: 'spaceGroup:14',
        observation: 'P 21/c: primitive, 2₁ along b, c glide across it',
      },
      {
        object: 'spaceGroup:225',
        observation: 'F m-3m: 4/m along a, -3 along the body diagonal',
      },
    ],
  },
  'assignment flowchart': {
    title: 'The assignment flowchart',
    summary:
      'Six questions in a fixed order: linear, more than one axis of order 3 or higher, a principal Cₙ, n C₂ across it, a σₕ, n σd. Asking them out of order is how a tetrahedron gets called C3v, which is why the high-order-axis question comes second.',
    examples: [
      {
        object: 'molecule:methane',
        observation: 'Question 2 answers yes: four C3 axes, so Td',
      },
      {
        object: 'molecule:boron-trifluoride',
        observation: 'C3, then 3 C2 across it, then σh: D3h',
      },
    ],
  },
  chirality: {
    title: 'Chirality',
    summary:
      'An object is chiral when it cannot be superimposed on its mirror image, and that happens exactly when its group holds no improper operation. So a chiral molecule is C₁, Cₙ, Dₙ, T, O or I, and nothing else.',
    examples: [
      {
        object: 'molecule:bromochlorofluoromethane',
        observation: 'C1: nothing but E, so it is chiral',
      },
      {
        object: 'molecule:allene',
        observation: 'D2d has an S4, so allene itself is achiral',
        note: 'A 1,3-disubstituted allene is D2, and chiral.',
      },
    ],
  },
  polarity: {
    title: 'Polarity',
    summary:
      'A molecule has a permanent dipole only when some direction survives every operation of its group. That restricts it to C₁, Cs, Cₙ and Cₙᵥ. A perpendicular C₂, a σₕ or an inversion centre each kill the dipole.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'C2v: the dipole lies along the C2 axis',
      },
      {
        object: 'molecule:carbon-dioxide',
        observation: 'D∞h: the two C=O dipoles cancel exactly',
      },
    ],
  },
  'stereographic projection': {
    title: 'Stereographic projection',
    summary:
      'A flat drawing of a point group: the sphere around the object projected onto a disc, upper points filled and lower ones open. Every crystallography text names groups this way, and two similar groups differ at a glance in it.',
    examples: [
      {
        object: 'molecule:water',
        observation: 'Four points, two mirror lines crossing at the centre',
      },
    ],
  },
  c1: {
    title: 'C₁',
    summary:
      'The group of order 1: the identity and nothing else. Any molecule with four different substituents on one centre lands here, and every one of them is chiral and polar.',
    examples: [
      { object: 'molecule:bromochlorofluoromethane', observation: 'h = 1' },
    ],
  },
  c2v: {
    title: 'C₂ᵥ',
    summary:
      'A C₂ axis with two σᵥ planes containing it: order 4, four one-dimensional irreducible representations. The commonest point group in a first course, and the table worth learning by heart.',
    examples: [
      { object: 'molecule:water', observation: 'E, C2, σv(xz), σv′(yz)' },
      { object: 'pointGroup:c2v', observation: 'The character table, in full' },
    ],
  },
  c2h: {
    title: 'C₂ₕ',
    summary:
      'A C₂ axis with a mirror plane perpendicular to it, order 4. The two together generate an inversion centre, so a C₂ₕ molecule is neither chiral nor polar and obeys the mutual exclusion rule.',
    examples: [
      {
        object: 'molecule:trans-dichloroethene',
        observation: 'E, C2, i, σh — and the inversion centre nobody put there',
      },
    ],
  },
  td: {
    title: 'Td',
    summary:
      'The tetrahedral group: four C₃ axes, three C₂, six S₄ and six σd, order 24, with irreducible representations A₁, A₂, E, T₁ and T₂. No inversion centre, which is what separates it from Oₕ.',
    examples: [
      { object: 'molecule:methane', observation: '24 operations, 5 classes' },
      {
        object: 'molecule:white-phosphorus',
        observation: 'P4, a bare Td cage',
      },
    ],
  },
  d2d: {
    title: 'D₂d',
    summary:
      'A C₂ principal axis with two C₂ across it, two σd bisecting those, and an S₄: order 8. What you get when two halves of a molecule are twisted 90° apart rather than lying flat.',
    examples: [
      {
        object: 'molecule:allene',
        observation: 'The two CH2 groups are perpendicular',
        note: 'Ethene, which is flat, is D2h instead.',
      },
    ],
  },
  d3d: {
    title: 'D₃d',
    summary:
      'A C₃ axis, three C₂ across it, three σd and an S₆ whose cube is an inversion centre: order 12. The group of staggered ethane and of chair cyclohexane.',
    examples: [
      {
        object: 'molecule:ethane-staggered',
        observation: 'The eclipsed conformer is D3h instead',
        note: 'The σh appears and the σd go.',
      },
      { object: 'molecule:cyclohexane-chair', observation: 'The same group' },
    ],
  },
  dinfh: {
    title: 'D∞ₕ',
    summary:
      'A linear molecule with a centre of inversion: infinitely many σᵥ along the axis, infinitely many C₂ across it, and a σₕ. Its partner C∞ᵥ is the linear group without the inversion centre.',
    examples: [
      {
        object: 'molecule:carbon-dioxide',
        observation: 'D∞h, because the two ends are identical',
      },
      {
        object: 'molecule:carbonyl-sulfide',
        observation: 'C∞v, because they are not',
      },
    ],
  },
};
