import type { SymmetryGlossaryEntry } from './types.ts';

/** What translation adds: lattices, cells and the coordinates inside them. */
export const LATTICE_TERMS: Record<string, SymmetryGlossaryEntry> = {
  lattice: {
    title: 'Lattice',
    summary:
      'An infinite array of points with identical surroundings, generated by three non-coplanar translation vectors. It is a scaffold and not the atoms: a crystal is a motif placed at every lattice point.',
    examples: [
      {
        object: 'spaceGroup:1',
        observation: 'P1: one atom per cell, repeated by translation alone',
      },
    ],
  },
  motif: {
    title: 'Motif',
    summary:
      'The group of atoms attached to one lattice point. Crystal = lattice + motif, and the motif is what differs between diamond and silicon while the lattice is the same.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: 'Rock salt: one Na plus one Cl on a face-centred lattice',
      },
    ],
  },
  'unit cell': {
    title: 'Unit cell',
    summary:
      'The box that fills space by translation with no gaps and no overlaps. It is chosen to show the symmetry of the crystal rather than to be as small as possible, which is why centred cells exist at all.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: '4 lattice points in the conventional cubic cell',
      },
    ],
  },
  'lattice parameters': {
    title: 'Lattice parameters',
    summary:
      'The six numbers a, b, c, α, β, γ describing the cell — three edges and three angles. The crystal system constrains them: cubic forces a = b = c and every angle 90°, triclinic constrains nothing.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: 'Rock salt: a = b = c = 5.64 Å, α = β = γ = 90°',
      },
    ],
  },
  'primitive cell': {
    title: 'Primitive cell',
    summary:
      'A cell holding exactly one lattice point. Every lattice has one, but it often hides the symmetry: the primitive cell of a face-centred cubic lattice is a rhombohedron with 60° angles, which shows none of the cubic symmetry it belongs to.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: 'Conventional cell 4 points, primitive cell 1',
        note: 'A quarter of the volume, and none of the visible symmetry.',
      },
    ],
  },
  'centred cell': {
    title: 'Centred cell',
    summary:
      'A conventional cell carrying extra lattice points: I at the body centre, F on every face centre, A, B or C on one pair of faces, R for a rhombohedral lattice on hexagonal axes. Each extra point multiplies the number of general positions by the same factor.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: 'F: 48 point-group operations × 4 points = 192 positions',
      },
      { object: 'spaceGroup:5', observation: 'C2: 2 points, so 4 positions' },
    ],
  },
  'bravais lattice': {
    title: 'Bravais lattice',
    summary:
      'One of the 14 distinct lattice types in three dimensions: the 7 crystal systems with the centrings each allows. There are only 14 because every other combination either repeats one already listed or breaks the symmetry of its own system.',
    examples: [
      {
        object: 'spaceGroup:1',
        observation: 'Triclinic P, the least symmetric of the fourteen',
      },
    ],
  },
  'crystal system': {
    title: 'Crystal system',
    summary:
      'One of the seven families a cell belongs to, fixed by its minimum symmetry: triclinic, monoclinic, orthorhombic, tetragonal, trigonal, hexagonal, cubic. The 230 space groups split 2, 13, 59, 68, 25, 27 and 36 between them.',
    examples: [
      {
        object: 'spaceGroup:14',
        observation: 'Monoclinic: one twofold direction, so only β differs',
      },
    ],
  },
  'fractional coordinates': {
    title: 'Fractional coordinates',
    summary:
      'A position given as fractions of the cell edges, so (½, 0, 0) is half-way along a. They are what a space group operates on and what a CIF file stores, because they do not depend on the size of the cell.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: 'Na at (0, 0, 0) and Cl at (½, 0, 0) is rock salt',
      },
    ],
  },
  'asymmetric unit': {
    title: 'Asymmetric unit',
    summary:
      'The smallest part of the cell the operations rebuild everything else from. Its volume is the cell volume divided by the number of general positions, so a quarter of the cell in P2₁/c and a 192nd in Fm-3m. A structure is published as this plus the space group.',
    examples: [
      {
        object: 'spaceGroup:14',
        observation: 'One quarter of the cell: one molecule becomes four',
      },
    ],
  },
  'crystallographic restriction theorem': {
    title: 'Crystallographic restriction',
    summary:
      'Only 1-, 2-, 3-, 4- and 6-fold rotations are compatible with a lattice. Fivefold and sevenfold axes cannot tile the plane or space, which is why no crystal has one — and why quasicrystals, which do diffract fivefold, are not periodic at all.',
    examples: [
      {
        object: 'wallpaper:p6m',
        observation: 'Sixfold centres tile the plane; fivefold ones leave gaps',
      },
    ],
  },
  supercell: {
    title: 'Supercell',
    summary:
      'A cell built from several unit cells, written n × m × p. Used to show a structure in a larger context, to model a defect or an ordered substitution, or to see how the packing continues. Its symmetry is usually lower than that of the cell it was built from.',
    examples: [
      {
        object: 'spaceGroup:225',
        observation: '2 × 2 × 2 rock salt: 32 Na and 32 Cl',
      },
    ],
  },
};
