import type { PointOperation } from '../../symmetry/operations.ts';
import { applyMatrix, rotationMatrix } from '../../symmetry/point/mat3.ts';
import type { Vec3 } from '../../symmetry/point/vec3.ts';
import {
  addVectors,
  crossProduct,
  normalizeVector,
  scaleVector,
  subtractVectors,
  vectorDistance,
} from '../../symmetry/point/vec3.ts';
import { operationsOf } from '../../symmetry/pointGroups.ts';

const DEGREE = Math.PI / 180;

/** One atom of a molecule: an element symbol and a position in ångström. */
export interface MoleculeAtom {
  readonly element: string;
  readonly position: Vec3;
}

/**
 * The two hydrogens on a tetrahedral centre whose other two bonds are `first`
 * and `second`: in the plane that bisects them, at `angle` to each other.
 */
export function sp3Pair(
  centre: Vec3,
  first: Vec3,
  second: Vec3,
  length: number,
  angle: number,
): [Vec3, Vec3] {
  const a = normalizeVector(subtractVectors(first, centre));
  const b = normalizeVector(subtractVectors(second, centre));
  const bisector = normalizeVector(scaleVector(addVectors(a, b), -1));
  const normal = normalizeVector(crossProduct(a, b));
  const half = (angle * DEGREE) / 2;
  const along = scaleVector(bisector, length * Math.cos(half));
  const across = scaleVector(normal, length * Math.sin(half));
  return [
    addVectors(centre, addVectors(along, across)),
    addVectors(centre, subtractVectors(along, across)),
  ];
}

/**
 * Every image of `seed` under `operations`, with the duplicates dropped.
 *
 * This is how the molecules that cannot be written down are built — `T`, `Tₕ`,
 * `S₄` — because a structure generated by a group **is** symmetric under it, to
 * machine precision, where a hand-placed one is only nearly so.
 */
export function orbitAtoms(
  seed: readonly MoleculeAtom[],
  operations: readonly PointOperation[],
  tolerance = 1e-6,
): MoleculeAtom[] {
  const out: MoleculeAtom[] = [];
  for (const operation of operations) {
    for (const atom of seed) {
      const position = applyMatrix(operation.matrix, atom.position);
      const seen = out.some(
        (one) =>
          one.element === atom.element &&
          vectorDistance(one.position, position) <= tolerance,
      );
      if (!seen) out.push({ element: atom.element, position });
    }
  }
  return out;
}

/** `element` at each of the positions. */
export function atomsAt(
  element: string,
  positions: readonly Vec3[],
): MoleculeAtom[] {
  return positions.map((position) => ({ element, position }));
}

/** The positions, with any repeated one dropped. */
export function dedupePositions(
  points: readonly Vec3[],
  tolerance = 1e-6,
): Vec3[] {
  const out: Vec3[] = [];
  for (const point of points) {
    if (out.some((one) => vectorDistance(one, point) <= tolerance)) continue;
    out.push(point);
  }
  return out;
}

/**
 * A molecule from one atom per orbit, expanded by the operations of its group in
 * the standard orientation: principal axis along **z**, a `C₂` along **x**, and
 * the first σ_v the **xz** plane.
 *
 * Placing one atom and letting the group place the rest is what makes a taught
 * example exactly symmetric. A structure typed out atom by atom is symmetric
 * only to the precision of the typing, and the detector has to be told a
 * tolerance loose enough to forgive it — which is the tolerance that starts
 * calling a `D₃` ethane `D₃d`.
 */
export function expandSeed(
  group: string,
  seed: readonly MoleculeAtom[],
): MoleculeAtom[] {
  return orbitAtoms(seed, operationsOf(group));
}

/**
 * A bond drawn in a plane: from `centre`, at `angle` degrees from the direction
 * of `toward`, turned about `normal`. How every sp² substituent is placed.
 */
export function planarBond(
  centre: Vec3,
  toward: Vec3,
  angle: number,
  length: number,
  normal: Vec3 = [1, 0, 0],
): Vec3 {
  const direction = normalizeVector(subtractVectors(toward, centre));
  const turned = applyMatrix(
    rotationMatrix(normalizeVector(normal), (angle * Math.PI) / 180),
    direction,
  );
  return addVectors(centre, scaleVector(turned, length));
}
