import { identityMatrix, matricesEqual } from './integerMatrix.ts';
import {
  compose,
  identityOperation,
  operationKey,
  wrapTwelfths,
} from './operation.ts';
import type { CrystalOperation, Dimension, IntegerMatrix } from './types.ts';

/**
 * Every coset representative generated by `generators`, modulo the lattice
 * translations: the whole group when the generators generate it.
 *
 * A breadth-first closure over exact integer keys, so it terminates on any input
 * whose rotation parts have finite order. The identity comes first.
 *
 * @throws When the closure passes `limit` operations, which means the generators
 *   are not those of a crystallographic group.
 */
export function closure<D extends Dimension>(
  generators: ReadonlyArray<CrystalOperation<D>>,
  limit = 1536,
): Array<CrystalOperation<D>> {
  const dimension = (generators[0]?.rotation.length ?? 3) as D;
  const identity = identityOperation(dimension);
  const found = new Map<string, CrystalOperation<D>>([
    [operationKey(identity), identity],
  ]);
  const queue: Array<CrystalOperation<D>> = [identity];
  // The queue grows while it is read, which is what makes this a closure.
  for (const current of queue) {
    for (const generator of generators) {
      const next = compose(generator, current);
      const key = operationKey(next);
      if (found.has(key)) continue;
      found.set(key, next);
      queue.push(next);
      if (queue.length > limit) {
        throw new RangeError(
          `the generators do not close within ${limit} operations`,
        );
      }
    }
  }
  return queue;
}

/** The rotation parts occurring in a list, one per distinct matrix. */
export function distinctRotations(
  operations: ReadonlyArray<CrystalOperation<Dimension>>,
): IntegerMatrix[] {
  const seen = new Map<string, IntegerMatrix>();
  for (const operation of operations) {
    const rotation = operation.rotation;
    let key = '';
    for (const row of rotation) {
      for (let j = 0; j < rotation.length; j++) {
        key += `${row[j] ?? 0},`;
      }
    }
    if (!seen.has(key)) seen.set(key, rotation);
  }
  return [...seen.values()];
}

/**
 * The lattice translations of a group: the translation parts of the operations
 * whose rotation part is the identity. `[[0,0,0]]` for a primitive lattice, four
 * vectors for a face-centred one.
 */
export function centringTranslations(
  operations: ReadonlyArray<CrystalOperation<Dimension>>,
): number[][] {
  const dimension = operations[0]?.rotation.length ?? 3;
  const identity = identityMatrix(dimension);
  const translations: number[][] = [];
  for (const operation of operations) {
    if (!matricesEqual(operation.rotation, identity)) continue;
    const translation = new Array<number>(dimension).fill(0);
    for (let axis = 0; axis < dimension; axis++) {
      translation[axis] = wrapTwelfths(operation.translation[axis] ?? 0);
    }
    translations.push(translation);
  }
  return translations.length === 0
    ? [new Array<number>(dimension).fill(0)]
    : translations;
}
