import { expect, test } from 'vitest';

import { finitePointGroups, pointGroupById } from '../../data/pointGroups.ts';
import { reflectionOperation } from '../operations.ts';
import {
  closeGroup,
  conjugacyClasses,
  generatorsOf,
  labelOperations,
  operationsOf,
} from '../pointGroups.ts';

test('every finite group closes to exactly its order', () => {
  for (const group of finitePointGroups()) {
    expect([group.id, operationsOf(group.id).length]).toStrictEqual([
      group.id,
      group.order,
    ]);
  }
  expect(operationsOf('Ih')).toHaveLength(120);
  expect(operationsOf('D6d')).toHaveLength(24);
});

test('the conjugacy classes are the classes the catalogue prints', () => {
  for (const group of finitePointGroups()) {
    const found = conjugacyClasses(operationsOf(group.id))
      .map((one) => one.length)
      .toSorted((a, b) => a - b);
    const expected = group.classes
      .map((one) => one.size)
      .toSorted((a, b) => a - b);
    expect([group.id, found]).toStrictEqual([group.id, expected]);
  }
});

test('a continuous group has no operation list', () => {
  expect(() => operationsOf('Cinfv')).toThrow('continuous group');
  expect(() => operationsOf('Dinfh')).toThrow('continuous group');
});

test('a group is generated by two operations or three', () => {
  expect(generatorsOf(pointGroupById('C1'))).toHaveLength(0);
  expect(generatorsOf(pointGroupById('D6h'))).toHaveLength(3);
  expect(
    generatorsOf(pointGroupById('C3v')).map((one) => one.label),
  ).toStrictEqual(['C3', 'σ']);
  // D_nd is generated by its S_2n, not by its C_n.
  expect(generatorsOf(pointGroupById('D4d'))[0]?.label).toBe('S8');
});

test('generators that do not close are refused rather than run forever', () => {
  expect(() =>
    closeGroup(generatorsOf(pointGroupById('D6h')), { limit: 8 }),
  ).toThrow('do not close within 8 operations');
});

test('a mirror is named for where it sits relative to the principal axis', () => {
  expect(labels('C2v')).toStrictEqual(['σv', 'σv']);
  expect(labels('C2h')).toStrictEqual(['σh']);
  // Every vertical plane of D4h holds a perpendicular C2, so which half is
  // called σd is a convention, not something an operation carries.
  expect(labels('D4h')).toStrictEqual(['σh', 'σv', 'σv', 'σv', 'σv']);
  expect(labels('D3d')).toStrictEqual(['σd', 'σd', 'σd']);
  expect(labels('D3h')).toStrictEqual(['σh', 'σv', 'σv', 'σv']);
  // No single principal axis, so no plane can be named for one.
  expect(labels('Td')).toStrictEqual(['σ', 'σ', 'σ', 'σ', 'σ', 'σ']);
});

test('a plane keeps its own label when there is no principal axis to name it by', () => {
  const plane = reflectionOperation([0, 0, 1]);
  expect(labelOperations([plane], null)[0]?.label).toBe('σ');
  expect(labelOperations([plane], [0, 0, 1])[0]?.label).toBe('σh');
});

test('the operations of Oh are 24 proper and 24 improper', () => {
  const operations = operationsOf('Oh');
  const proper = operations.filter(
    (one) => one.kind === 'E' || one.kind === 'Cn',
  );
  expect(proper).toHaveLength(24);
  expect(operations).toHaveLength(48);
  expect(operations.filter((one) => one.kind === 'i')).toHaveLength(1);
  expect(operations.filter((one) => one.kind === 'sigma')).toHaveLength(9);
  expect(operations.filter((one) => one.kind === 'Sn')).toHaveLength(14);
});

/** The plane labels of a group, sorted. */
function labels(group: string): readonly string[] {
  return operationsOf(group)
    .map((one) => one.label)
    .filter((label) => label.startsWith('σ'))
    .toSorted();
}
