/**
 * One address per molecular point group: what somebody searching `C2v character
 * table` or `Td symmetry` should land on.
 *
 * Every sentence is read off the group's own record — the axes and planes it is
 * built on, how many operations they make, its Hermann-Mauguin symbol, whether
 * it is chiral, and the molecule the library holds for it — so no two of the
 * fifty-three read alike. It is said in words, never in the character-table
 * header the group is stored under: what a search result shows is prose.
 */

import type { RouteMeta } from 'react-cheminfo/core';

import { characterTableOf } from '../data/characterTables.ts';
import { moleculesOfGroup } from '../data/molecules.ts';
import type { PointGroup } from '../data/pointGroups.ts';
import { POINT_GROUPS } from '../data/pointGroups.ts';

import { count, describe, withArticle } from './describe.ts';

/** `/point-groups/<slug>` for every point group the catalogue holds. */
export function pointGroupRoutes(): readonly RouteMeta[] {
  return POINT_GROUPS.map(pointGroupRoute);
}

/** The address, name and sentence of one point group. */
export function pointGroupRoute(group: PointGroup): RouteMeta {
  return {
    path: `/point-groups/${group.slug}`,
    title: titleOf(group),
    description: describe(baseOf(group), extrasOf(group)),
    short: group.schoenflies,
  };
}

function titleOf(group: PointGroup): string {
  if (!Number.isFinite(group.order)) {
    return `${group.schoenflies} point group — a linear molecule`;
  }
  if (group.hermannMauguin !== null) {
    return `${group.schoenflies} point group — order ${group.order}, Hermann-Mauguin ${group.hermannMauguin}`;
  }
  return `${group.schoenflies} point group — order ${group.order}`;
}

function baseOf(group: PointGroup): string {
  const operations = Number.isFinite(group.order)
    ? count(group.order, 'symmetry operation')
    : 'infinitely many symmetry operations';
  const classes = count(group.classes.length, 'class', 'classes');
  return `The ${group.schoenflies} point group is built on ${elementsOf(group)}: ${operations} in ${classes}.`;
}

/**
 * The axes and planes the group is generated by, said the way a chemist says
 * them out loud.
 *
 * The character-table header the group is stored under — `2S12^5`, `4C2′`,
 * `σv(xz)` — is the spelling of an operation, not of a sentence: a search
 * result and a link preview show this text to a person, so what goes in it is
 * `a six-fold axis, six two-fold axes across it`. The header row belongs on the
 * page, where it is a table.
 */
function elementsOf(group: PointGroup): string {
  const order = group.principalOrder;
  const axis = withArticle(`${fold(order)} axis`);
  // Two two-fold axes across a two-fold one are two *more* of the same, and
  // saying so is what keeps D2 from reading `a two-fold axis with two two-fold
  // axes`.
  const across =
    order === 2
      ? 'two more two-fold axes across it'
      : `${word(order)} two-fold axes across it`;
  switch (group.family) {
    case 'nonaxial':
      if (group.order === 1) return 'nothing but the identity';
      return group.centrosymmetric
        ? 'an inversion centre'
        : 'a single mirror plane';
    case 'Cn':
      return `a single ${fold(order)} rotation axis`;
    case 'Cnv':
      return `${axis} with ${word(order)} mirror planes through it`;
    case 'Cnh':
      return `${axis} with a mirror plane across it`;
    case 'Dn':
      return `${axis} with ${across}`;
    case 'Dnh':
      return `${axis}, ${across} and a horizontal mirror plane`;
    case 'Dnd':
      return `${axis}, ${across} and ${word(order)} mirror planes between them`;
    case 'Sn':
      return `${withArticle(`${fold(order)} improper axis`)}, a turn of ${360 / order}° followed by a reflection`;
    case 'cubic':
      return order === 3
        ? 'the four three-fold axes of a tetrahedron'
        : 'the three four-fold and four three-fold axes of a cube';
    case 'icosahedral':
      return 'the six five-fold axes of an icosahedron';
    case 'linear':
      return group.centrosymmetric
        ? 'an axis of infinite order, a mirror plane across it and the inversion'
        : 'an axis of infinite order, with mirror planes along it';
    default:
      throw new RangeError(
        `the ${String(group.family)} point groups have no sentence written for them`,
      );
  }
}

const NUMBER_WORDS = [
  'no',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
];

/** `three`, for the counts a point group reaches. */
function word(value: number): string {
  return NUMBER_WORDS[value] ?? String(value);
}

/** `three-fold`, as an axis is named. */
function fold(order: number): string {
  return `${word(order)}-fold`;
}

function extrasOf(group: PointGroup): ReadonlyArray<readonly string[]> {
  return [
    // The molecule first: the Hermann-Mauguin symbol is already in the title,
    // and `Ammonia (NH3) belongs to it` is what somebody searching for the
    // point group of a molecule typed.
    moleculeClauses(group),
    latticeClauses(group),
    shapeClauses(group),
    group.laueClass === null ? [] : [`Laue class ${group.laueClass}.`],
    tableClauses(group),
  ];
}

function latticeClauses(group: PointGroup): readonly string[] {
  if (group.hermannMauguin === null) {
    return [
      'No lattice allows this axis, so it is not one of the 32 crystal classes.',
      'Not one of the 32 crystal classes.',
    ];
  }
  return [
    `Hermann-Mauguin ${group.hermannMauguin}, one of the 32 crystal classes, ${group.crystalSystem ?? ''}.`,
    `Hermann-Mauguin ${group.hermannMauguin}, one of the 32 crystal classes.`,
    `Hermann-Mauguin ${group.hermannMauguin}.`,
  ];
}

function moleculeClauses(group: PointGroup): readonly string[] {
  const [first] = moleculesOfGroup(group.id);
  if (first === undefined) return [];
  const formula = `${first.formula} belongs to it.`;
  // The clause opens a sentence, so a name the library writes in lower case —
  // `anti meso-1,2-dichloro-1,2-difluoroethane` — is offered by its formula
  // instead of starting a sentence in lower case.
  return /^[A-Z]/.test(first.name)
    ? [`${first.name} (${first.formula}) belongs to it.`, formula]
    : [formula];
}

function shapeClauses(group: PointGroup): readonly string[] {
  const clauses: string[] = [];
  if (group.chiral && group.polar) {
    clauses.push(
      'Chiral and polar: a molecule in it is optically active and may carry a dipole.',
      'Chiral and polar.',
    );
  } else if (group.chiral) {
    clauses.push(
      'Chiral: every operation is a rotation, so a molecule in it is optically active.',
      'Chiral, so a molecule in it is optically active.',
    );
  } else if (group.polar) {
    clauses.push(
      'Polar: one direction is left free, so a molecule in it may carry a dipole.',
      'Polar, so a molecule in it may carry a dipole.',
    );
  }
  if (group.centrosymmetric) {
    clauses.push(
      'Centrosymmetric: it holds the inversion, so every irrep is labelled g or u.',
      'Centrosymmetric, so every irrep is labelled g or u.',
      'Centrosymmetric.',
    );
  } else if (!group.chiral && !group.polar) {
    clauses.push(
      'It holds improper operations but no inversion, so it is neither chiral nor polar.',
      'Neither chiral nor polar, and it holds no inversion.',
    );
  }
  return clauses;
}

function tableClauses(group: PointGroup): readonly string[] {
  if (characterTableOf(group.id) !== undefined) {
    return [
      'Its character table is here, with those classes as the columns.',
      'Its character table is here.',
    ];
  }
  return [
    'The site ships no character table for it, only its operations.',
    'The site ships no character table for it.',
  ];
}
