import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { argv, stdout } from 'node:process';

import type { CrystalOperation } from '../src/symmetry/core/index.ts';
import {
  centringTranslations,
  distinctRotations,
  formatOperation,
  parseOperation,
  pointGroupName,
} from '../src/symmetry/core/index.ts';
import {
  crystalSystemOf,
  hasInversionAtOrigin,
  isCentrosymmetric,
  isSohncke,
  isSymmorphic,
  laueClassOf,
  uniqueAxisOf,
} from '../src/symmetry/spaceGroupDerivation.ts';

/** One entry of the extracted table, exactly as it is on disk. */
interface SourceEntry {
  spaceGroup: number;
  variant: number;
  HM: string;
  hall?: string;
  latticeCentering: string;
  abbreviatedSymbol: string;
  crystalSystem: string;
  equivalentArray: string[];
}

/**
 * The pre-2002 spelling of the five symbols the source writes with an *e*
 * glide. Most published CIFs and every textbook printed before about 2005 use
 * these, so a reader without them rejects good files. They are an alias table
 * and not a derivation: which of the two glide vectors the old symbol named is
 * a convention, not a fact about the group.
 */
const LEGACY_GLIDE_SYMBOLS = new Map<number, string>([
  [39, 'A b m 2'],
  [41, 'A b a 2'],
  [64, 'C m c a'],
  [67, 'C m m a'],
  [68, 'C c c a'],
]);

const ROOT = join(import.meta.dirname, '..');
const SOURCE = 'src/symmetry/core/__tests__/data/spaceGroups.json';
const TARGET = join(ROOT, 'src/data/spaceGroupRows.ts');

const entries = JSON.parse(
  readFileSync(argv[2] ?? join(ROOT, SOURCE), 'utf8'),
) as SourceEntry[];

const fullByNumber = new Map<number, string>();
for (const entry of entries) {
  if (entry.variant === 0) fullByNumber.set(entry.spaceGroup, symbol(entry.HM));
}

const rows: string[] = [];
let operationCount = 0;
for (const entry of entries) {
  const operations = entry.equivalentArray.map((triplet) =>
    parseOperation(triplet.trim(), 3),
  );
  operationCount += operations.length;
  for (const [index, operation] of operations.entries()) {
    const printed = formatOperation(operation);
    const original = entry.equivalentArray[index]?.trim();
    if (printed !== original) {
      throw new Error(
        `${entry.spaceGroup}: "${original}" printed back as "${printed}"`,
      );
    }
  }
  const rotations = distinctRotations(operations);
  const crystalClass = pointGroupName(rotations, 3);
  const crystalSystem = crystalSystemOf(crystalClass);
  if (crystalSystem !== entry.crystalSystem.toLowerCase()) {
    throw new Error(
      `${entry.spaceGroup}: derived ${crystalSystem}, the source says ${entry.crystalSystem}`,
    );
  }
  rows.push(
    [
      entry.spaceGroup,
      entry.variant,
      symbol(entry.abbreviatedSymbol.replace(/\[\s*origin\s*[12]\s*]/, '')),
      fullByNumber.get(entry.spaceGroup) ?? '',
      symbol(entry.HM),
      LEGACY_GLIDE_SYMBOLS.get(entry.spaceGroup) ?? '',
      entry.hall === undefined ? '' : symbol(entry.hall),
      crystalSystem,
      entry.latticeCentering,
      entry.latticeCentering === 'R'
        ? centringTranslations(operations).length === 3
          ? 'hexagonal'
          : 'rhombohedral'
        : '',
      originChoiceOf(entry, operations),
      crystalSystem === 'monoclinic' ? uniqueAxisOf(rotations) : '',
      crystalClass,
      laueClassOf(rotations),
      `${flag(isCentrosymmetric(rotations))}${flag(isSohncke(rotations))}${flag(isSymmorphic(operations))}`,
      entry.equivalentArray.map((triplet) => triplet.trim()).join(';'),
    ].join('|'),
  );
}

/**
 * Origin choice 2 puts the inversion centre at the origin, so it is the setting
 * whose list holds a bare `-x,-y,-z`. The `[origin n]` display string is read
 * only to know whether the number offers a choice at all — its own spacing is
 * inconsistent either side of number 74 — and the value it carries is asserted
 * against what the operations say.
 */
function originChoiceOf(
  entry: SourceEntry,
  operations: ReadonlyArray<CrystalOperation<3>>,
): string {
  const tag = /\[\s*origin\s*(?<choice>[12])\s*]/.exec(entry.abbreviatedSymbol);
  if (tag === null) return '';
  const derived = hasInversionAtOrigin(operations) ? '2' : '1';
  if (derived !== tag.groups?.choice) {
    throw new Error(
      `${entry.spaceGroup} v${entry.variant}: the label says origin ${tag.groups?.choice}, the operations say ${derived}`,
    );
  }
  return derived;
}

/** A symbol with its origin suffix dropped and its runs of spaces collapsed. */
function symbol(text: string): string {
  return text
    .replace(/:[12]$/, '')
    .replaceAll(/\s+/g, ' ')
    .trim();
}

function flag(value: boolean): string {
  return value ? '1' : '0';
}

const header = `// Generated by scripts/generateSpaceGroups.ts from
// ${SOURCE} — do not edit by hand.
//
// One setting to a row, pipe separated:
//   number | variant | hmShort | hmFull | hmSetting | hmLegacy | hall |
//   crystalSystem | centring | axes | originChoice | uniqueAxis |
//   crystalClass | laueClass | flags | operations
//
// \`flags\` is centrosymmetric, sohncke and symmorphic as 1 or 0; an empty field
// means the setting has no such value; \`operations\` is the coset list with the
// centring expanded, semicolon separated.

/** The 521 settings of the 230 space groups, encoded one to a row. */
export const SPACE_GROUP_ROWS: readonly string[] = [
`;

const body = rows
  .map(
    (row) =>
      `  '${row.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)}',\n`,
  )
  .join('');
writeFileSync(TARGET, `${header}${body}];\n`, 'utf8');

stdout.write(
  `${rows.length} settings, ${operationCount} operations, written to ${TARGET}\n`,
);
